# Generated by Django 3.2.5 on 2021-07-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210721_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custommer',
            new_name='customer',
        ),
    ]
