# Generated by Django 3.2.5 on 2021-07-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
