# Generated by Django 3.2.5 on 2021-08-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210730_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
