# Generated by Django 3.2.5 on 2021-08-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelcon',
        ),
    ]
